# Generated by Django 2.2.2 on 2019-06-12 10:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='', max_length=100)),
                ('description', models.CharField(default='', max_length=10000)),
                ('date', models.DateField(default=datetime.datetime.now)),
            ],
        ),
    ]
