# Generated by Django 2.2.2 on 2019-06-12 13:42

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_categorie'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auteur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='', max_length=100)),
                ('prenom', models.CharField(default='', max_length=100)),
                ('dateNaissance', models.DateField(default=datetime.datetime.now)),
                ('pseudo', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='article',
            old_name='description',
            new_name='contenu',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='nom',
            new_name='titre',
        ),
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='article',
            name='auteur',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='articles.Auteur'),
        ),
    ]
