# Generated by Django 2.2.2 on 2019-06-11 09:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartesmagic',
            name='nom',
        ),
        migrations.AddField(
            model_name='cartesmagic',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 6, 11, 9, 54, 52, 362857, tzinfo=utc)),
        ),
    ]
