# Generated by Django 2.2.2 on 2019-06-11 09:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190611_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartesmagic',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 6, 11, 9, 58, 4, 655942, tzinfo=utc)),
        ),
    ]
