# Generated by Django 2.2.2 on 2019-06-11 10:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190611_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartesmagic',
            name='image',
            field=models.CharField(default='', max_length=10000),
        ),
        migrations.AddField(
            model_name='cartesmagic',
            name='nom',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='cartesmagic',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 6, 11, 10, 10, 27, 180046, tzinfo=utc)),
        ),
    ]
