# Generated by Django 2.2.2 on 2019-06-12 10:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190611_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartesmagic',
            name='date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
